# Generated by Django 4.1.1 on 2023-06-13 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RequestsLicense', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestslicense',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
